# Generated by Django 2.2.1 on 2021-01-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Event Registration'},
        ),
    ]
