# Generated by Django 2.2.1 on 2021-01-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
