# Generated by Django 2.2.1 on 2021-01-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=100)),
                ('type_of_donation', models.CharField(max_length=100)),
                ('amount', models.CharField(default='$100', max_length=50)),
                ('comments', models.TextField(blank=True, max_length=1024)),
            ],
        ),
    ]
