# Generated by Django 2.2.1 on 2021-01-07 03:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
