# Generated by Django 2.2.1 on 2021-01-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_remove_program_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Program Registration'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'All Program'},
        ),
        migrations.AlterField(
            model_name='application',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City/Region/State'),
        ),
        migrations.AlterField(
            model_name='application',
            name='company',
            field=models.CharField(max_length=255, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Description of your youth programs'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='importance',
            field=models.TextField(verbose_name='Why is the program you are applying for important to you?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='website',
            field=models.CharField(max_length=255, verbose_name='Website Link'),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of Program'),
        ),
    ]
