# Generated by Django 2.2.1 on 2021-01-09 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='event',
            new_name='workshop',
        ),
    ]
