# Generated by Django 2.2.1 on 2021-01-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_auto_20210109_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Workshop Registration'},
        ),
    ]
