# Generated by Django 2.2.1 on 2021-01-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='org_address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='city',
            new_name='org_city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='country',
            new_name='org_country',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='org_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone',
            new_name='org_phone',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telephone',
            new_name='org_website',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='title',
            new_name='person_email',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='website',
            new_name='person_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='categories',
        ),
        migrations.AddField(
            model_name='customuser',
            name='person_org_title',
            field=models.CharField(default='Director', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='person_phone',
            field=models.CharField(default='0712345067', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
