# Generated by Django 2.2.1 on 2021-01-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Chat',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='chat',
            name='categories',
            field=models.ManyToManyField(related_name='posts', to='chatroom.Category'),
        ),
    ]
